import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import {
	AiFillLinkedin,
	AiFillYoutube,
	AiFillInstagram,
	AiFillGithub,
} from 'react-icons/ai';
import Image from 'next/image';
import dev from '../public/developer.gif';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import web1 from '../public/web1.png';
import { useState } from 'react';

export default function Home() {
	const [darkMode, setDarkMode] = useState(false);
	return (
		<div className={darkMode ? 'dark' : ''}>
			<Head>
				<title>MooSeon Portfolio</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-slate-900">
				<section className="min-h-screen">
					<nav className="py-10 mb-12 flex justify-between">
						<h1 className="text-xl font-burtons dark:text-slate-50">
							DevelopedbyMS
						</h1>
						<ul className="flex items-center">
							<li>
								<BsFillMoonStarsFill
									onClick={() => setDarkMode(!darkMode)}
									className="cursor-pointer text-2xl dark:text-slate-300"
								/>
							</li>
							<li>
								<a
									className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
									href="#"
								>
									Resume
								</a>
							</li>
						</ul>
					</nav>
					<div className="text-center p-10">
						<h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
							MooSeon PARK
						</h2>
						<h3 className="text-2xl py-2 md:text-3xl dark:text-slate-50">
							FrontEnd Developer
						</h3>
						<p className="text-md py-5 leading-8 text-gray-800 md:text-xl dark:text-slate-400">
							Thanks for visiting my webpage!
							<br />
							I'm looking for an opportunity to make the world a better place by
							technology and business.
						</p>
					</div>
					<div className="text-5xl flex justify-center gap-16 py-3 text-gray-700 dark:text-slate-300">
						<AiFillLinkedin />
						<AiFillGithub />
						<AiFillInstagram />
						<AiFillYoutube />
					</div>
					<div className="relative rounded-full items-center w-80 mt-20 mx-auto">
						<Image src={dev} />
					</div>
				</section>
				<section>
					<div>
						<h3 className="text-3xl py-1 mt-20 dark:text-slate-50">
							Services I offer
						</h3>
						<p className="text-md py-2 leading-8 text-gray-800 dark:text-slate-400">
							It is a long established fact that a reader will be distracted by
							the readable content of a page when looking at its layout. The
							point of using Lorem Ipsum is that it has a more-or-less normal
							distribution of letters, as opposed to using 'Content here,
							content here', making it look like readable English. Many desktop
							publishing packages and web page editors now use Lorem Ipsum as
							their default model text, and a search for 'lorem ipsum' will
							uncover many web sites still in their infancy. Various versions
							have evolved over the years, sometimes by accident, sometimes on
							purpose (injected humour and the like).
						</p>
					</div>
					<div className="lg:flex gap-10">
						<div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
							<Image src={code} width={100} height={100} className="mx-auto" />
							<h3 className="text-lg font-medium pt-8 pb-2 ">Skills I use</h3>
							<h4 className="py-4 text-teal-600">Learning & Growing with</h4>
							<p className="text-gray-800 py-1">HTML/CSS</p>
							<p className="text-gray-800 py-1">JAVASCRIPT</p>
							<p className="text-gray-800 py-1">REACT.JS</p>
						</div>
						<div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
							<Image
								src={consulting}
								width={100}
								height={100}
								className="mx-auto"
							/>
							<h3 className="text-lg font-medium pt-8 pb-2 ">Skills I use</h3>
							<h4 className="py-4 text-teal-600">Learning & Growing with</h4>
							<p className="text-gray-800 py-1">HTML/CSS</p>
							<p className="text-gray-800 py-1">JAVASCRIPT</p>
							<p className="text-gray-800 py-1">REACT.JS</p>
						</div>
					</div>
				</section>
				<section>
					<div>
						<h3 className="text-3xl py-1 dark:text-slate-50">Portfolio</h3>
						<p className="text-gray-800 py-1 dark:text-slate-400">HTML/CSS</p>
					</div>
					<div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
						<div className="basis-1/3 flex-1">
							<Image
								src={web1}
								className="rounded-lg object-cover"
								width={'100%'}
								height={'100%'}
								layout="responsive"
							/>
						</div>
						<div className="basis-1/3 flex-1">
							<Image
								src={web1}
								className="rounded-lg object-cover"
								width={'100%'}
								height={'100%'}
								layout="responsive"
							/>
						</div>
						<div className="basis-1/3 flex-1">
							<Image
								src={web1}
								className="rounded-lg object-cover"
								width={'100%'}
								height={'100%'}
								layout="responsive"
							/>
						</div>
					</div>
				</section>
			</main>
		</div>
	);
}
