import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs';

export default function Home() {
	return (
		<div>
			<Head>
				<title>MooSeon Portfolio</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<p>lorem</p>
			<main>
				<section className="min-h-screen">
					<nav className="py-10 mb-12 flex justify-between">
						<h1>developedbyed</h1>
						<ul>
							<li>
								<BsFillMoonStarsFill />
							</li>
							<li>
								<a href="#">Resume</a>
							</li>
						</ul>
					</nav>
				</section>
			</main>
		</div>
	);
}
